Repository betterscientificsoftware/bssw.io, pull requests merged in 2021-03, with the labels that each got.

#727 Move wikize_refs.py to utils/, add some tests, change to argparse, edits to doc (#363, #702)
  Articles/Blog/ReferencesInMarkdownHybridApproach-wikized.md
  Articles/Blog/ReferencesInMarkdownHybridApproach.md
  Articles/Blog/wikize_refs.py
  utils/.gitignore
  utils/CMakeLists.txt
  utils/README.md
  utils/run_tests.sh
  utils/tests/CMakeLists.txt
  utils/tests/run_wikize_ref_diff_test.cmake
  utils/tests/test_wikizer.md
  utils/wikize_refs.py
Labels: scope: site-internal, type: enhancement

#721 Add Scaling Yourself as a Software Developer cc article
  CuratedContent/ScalingYourselfSoftwareDeveloper.md
Labels: content: curated

#742 Added more guidance on event deck text
  docs/pages/bssw/bssw_styling_event.md
Labels: content: updates

#741 Created event for P-RESC'21
  Events/2021-06-P-RECS21.md
Labels: content: event

#714 Removing categories metadata
  CuratedContent/ClaimsAboutSoftwareEnginScienceReview.md
  CuratedContent/CodeComplete2ndEdition.md
  CuratedContent/ConstructiveCodeCritique.md
  CuratedContent/ContainerMythbusters.md
  CuratedContent/CreativeCommons.md
  CuratedContent/DevelopingConfiguringBuildingAndDeployingHpcSwUNPUB.md
  CuratedContent/DocumentationTools.md
  CuratedContent/IDEASSoftwareProductivityProject.md
  CuratedContent/NationalRSEOrgs.md
  CuratedContent/OSSSustainabilityResources.md
  CuratedContent/PsipPodcast.md
  CuratedContent/PublishingCseSw.md
  CuratedContent/RemoteWorking.md
  CuratedContent/SwTestingUdacity.md
  CuratedContent/UsingPersonalKanban.md
  Events/Workshop.RSE-HPE2020.md
  Events/Workshop.SE4Science21.md
  Events/hpcbp-044-testingpractices.md
  Events/panel.RemoteWorking0520.md
Labels: scope: site-internal

#713 Categories in Metadata Guide
  docs/pages/bssw/bssw_content_metadata.md
  docs/pages/bssw/bssw_styling_common.md
  docs/pages/bssw/bssw_styling_curated.md
  docs/pages/bssw/bssw_styling_event.md
  docs/pages/bssw/bssw_styling_originalarticles.md
Labels: scope: site-internal

#763 Remove references to "categories" metadata tag
  docs/pages/bssw/bssw_content_publishing.md
Labels: scope: site-internal

#754 Updated README for move of images to bssw.io/images/ directory (#738)
  images/README.md
Labels: scope: site-internal

#752 Tools needed to convert images to local repo refs (#703, #738)
  utils/convert_images_ref_to_rel_path.py
  utils/convert_images_ref_to_rel_path_all.sh
Labels: scope: site-internal, status: ready for EB discussion

#753 Remove tests/ directory (#751)
  test/README.md
  test/test_001_fail.md
  test/test_002_pass.md
  test/test_003_pass.md
  test/test_004_pass.md
  test/test_005_pass.md
  test/test_006_pass.md
  test/test_007_pass.md
Labels: scope: site-internal

#750 Update docs for updated citations/references policy (#702)
  Articles/Blog/ReferencesInMarkdownHybridApproach-wikized.md
  Articles/Blog/ReferencesInMarkdownHybridApproach.md
  Articles/Blog/WhenNotToWriteAutomatedTests-src.md
  Articles/Blog/WhenNotToWriteAutomatedTests.md
  docs/.gitignore
  docs/Gemfile
  docs/pages/bssw/bssw_content_publishing.md
  docs/pages/bssw/bssw_styling_originalarticles.md
  utils/README.md
Labels: type: enhancement

#764 GitHub Actions CC
  CuratedContent/GitHubActions.md
Labels: content: curated

#765 Only merge PR to 'preview' branch when 'preview' label is set and provide PR template with checklist (#695, #702, #744, #750, #330)
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/README.md
  .github/workflows/merge-pr-to-preview.yml
Labels: scope: site-internal

#740 SIAM CSE21 retrospective blog article
  Articles/Blog/2021-03-siam-cse21-retrospective.md
  Site/Homepage.md
Labels: content: blog, preview

#771 Follow-on tweaks to PR template from PR #765 (#695)
  .github/PULL_REQUEST_TEMPLATE.md
Labels: scope: site-internal

#772 Updated Link Title in GitHub actions CC
  CuratedContent/GitHubActions.md
Labels: bssw-digest:2021, content: curated
