Repository betterscientificsoftware/bssw.io, pull requests merged in 2022-09, with the labels that each got.

#1425 Changes to EB editorial roles and responsibilities
  docs/pages/bssw/bssw_teamresponsibilites.md
Labels: content: updates

#1426 EB docs: Point to editorial member list on bssw.io
  docs/pages/bssw/bssw_members.md
Labels: content: updates

#1429 Update links with 2023
  Site/BSSwFellowshipProgram/FellowsFAQ.md
Labels: preview

#1419 Eisty Peer Code Review blog post
  Articles/Blog/2022-09-peer-code-review.md
  images/Blog_2209_peer_review.png
Labels: content: blog, preview

#1433 Add September webinar
  CuratedContent/hpcbp-webinars-cc.md
Labels: content: curated, content: updates

#1434 October webinar
  Events/hpcbp-068-codereview.md
Labels: content: event

#1436 Updates per Matt's suggestions
  Articles/Blog/2022-09-peer-code-review.md
Labels: content: blog, content: updates, preview

#1440 Create 2022-10-hpcwd-blc.md
  Events/2022-10-hpcwd-blc.md
Labels: content: event, preview

#1441 Create 2022-11-sc22-sw-events.md
  Events/2022-11-sc22-sw-events.md
Labels: content: event, preview

#1444 Turn off checking for emphasis-as-header (MD036)
  .markdownlint.json
Labels: type: enhancement, scope: site-internal

#1430 Fix ngram link
  Articles/Blog/InclusiveLanguageCodeUpdateExample.md
Labels: preview

#1445 Correct publication date
  Articles/Blog/2022-09-SoftwareVariants.md
Labels: content: blog, content: updates

#1447 Create 2022-sustainable-research-pathways.md
  Events/2022-sustainable-research-pathways.md
Labels: preview

#1448 Carousel for October
  Site/Homepage.md
Labels: preview

#1449 Adding SRP event to carousel
  Site/Homepage.md
Labels: preview
