Repository betterscientificsoftware/bssw.io, pull requests merged in 2023-12, with the labels that each got.

#1889 Adding Tracks (deb set)
  Articles/Blog/InclusiveLanguageCodeUpdateExample.md
  Articles/Blog/IncreasingProductivityBroadeningParticipation.md
  Articles/Blog/LeadingAScientificSoftwareProject.md
  Articles/Blog/LessonsTransitioningExptoCS.md
  Articles/Blog/MakingOpenSourceResearchSwVisible.md
  Articles/Blog/OnDemandLearningForBetterScientificSoftware.md
  Articles/Blog/OutreachForBSSw.md
  Articles/Blog/PendingBSSwSiteLaunchNov2017.md
  Articles/Blog/PortingToHIP.md
  Articles/Blog/PracticesPerformancePortableEco.md
  Articles/Blog/PsipMainPage.md
  Articles/Blog/RSE-HPC-2020Workshop.md
  Articles/Blog/ResearchSoftwareEngineerANewCareerTrack.md
  Articles/Blog/ResearchSwScience.md
  Articles/Blog/RseStoriesPodcast.md
  Articles/Blog/SCSoftwareConference.md
  Articles/Blog/ScalingSmallTeamsToATeamOfTeams.md
  Articles/Blog/ScienceAndSocialMedia.md
  Articles/Blog/SoftwareAsCraft.md
  Articles/Blog/SoftwareSustainabilityMolecularSciences.md
  Articles/Blog/SoftwareVerification.md
  Articles/Blog/StreamliningSwDevptThroughContinuousIntegration.md
  Articles/Blog/SuperLUHowAdvancesInSwPracticesAreIncreasingSustainabilityAndCollaboration.md
  Articles/Blog/TestingNondeterministicResearchSoftware.md
  Articles/Blog/URSSI.md
  Articles/Blog/VisionFitnessForSoftwareProductivity.md
  Articles/Blog/WhatDoesThisLineDo.md
  Articles/Blog/WhenNotToWriteAutomatedTests.md
  Articles/Blog/WhyWeNeedStrategiesForWorkingRemotely.md
Labels: content: updates

#1890 Cleanup: curated content
  CuratedContent/10-number-test.md
  CuratedContent/AGCInDepth.md
  CuratedContent/AgileSoftwareDevelopmentMartin.md
  CuratedContent/AssociationForSoftwareTesting.md
  CuratedContent/BalterGithubCommunication.md
  CuratedContent/BestPracticesForScientificComputing.md
  CuratedContent/Bitbucket.md
  CuratedContent/ChecklistForBetterOpenSourceLibraries.md
  CuratedContent/ChooseALicense.md
  CuratedContent/CleanAndBeautifulCodeUNPUB.md
  CuratedContent/CollegevilleSeries.md
  CuratedContent/CommunityOrganizations2018.md
  CuratedContent/ComputationalScienceStackExchange.md
  CuratedContent/ContributorAgreements.md
  CuratedContent/CppUnit.md
  CuratedContent/CseCollaborationThroughSoftwareImprovingProductivityAndSustainability.SIAM-CSE17.md
Labels: content: updates, preview

#1893 Update DiscontinuingSoftwareProjects.md
  Articles/ShortArticles/DiscontinuingSoftwareProjects.md
Labels: content: curated, content: updates

#1895 Added meta data and publish date to CC on C++
  CuratedContent/NationalCyberDirectorRFI.md
Labels: content: curated, content: updates

#1888 Add CC for RFI regarding memory safe advocacy
  CuratedContent/NationalCyberDirectorRFI.md
Labels: content: curated, preview

#1892 remove bad files
  Articles/Blog/10-new-hacks.md
  Articles/Blog/2020-03-rate-your-project_UNPUB.md
Labels: content: updates

#1891 Add assigned tracks
  Articles/Blog/2018-11-messer-porting.md
  Articles/Blog/2019-05-siam-cse19.md
  Articles/Blog/2020-01-usrse.md
  Articles/Blog/2020-02-ideas-report.md
  Articles/Blog/2020-03-maintainers-drive-sustainability.md
  Articles/Blog/2020-03-making-myself-better.md
  Articles/Blog/2020-03-software-communities.md
  Articles/Blog/2020-05-lazy-approach.md
  Articles/Blog/2020-05-remote-spack.md
  Articles/Blog/2020-11-PSIP4HDF5.md
  Articles/Blog/2020-12-2021BSSwFellowshipAnnouncement.md
  Articles/Blog/2020-12-PerfPortabilityAndECP.md
  Articles/Blog/2021-01-ATPESC.md
  Articles/Blog/2021-02-AgileInSSwDev.md
  Articles/Blog/2021-03-2021BSSwFellowshipNSFAnnouncement.md
  Articles/Blog/2021-03-siam-cse21-retrospective.md
  Articles/Blog/2021-03-useful-practices-for-SEoMsDSP.md
  Articles/Blog/2021-04-RetrospectiveStrategies.md
  Articles/Blog/2021-04-SWMetricsInResearch.md
  Articles/Blog/2021-05-IntroToGPUProgramming.md
  Articles/Blog/2021-05-experiences-bssw-community-bof.md
  Articles/Blog/2021-06-ES4Blog.md
  Articles/Blog/2021-07-BSSwFellows21.md
  Articles/Blog/2021-07-RateYourProject.md
  Articles/Blog/2021-08-IntegratingInterns.md
  Articles/Blog/2021-08-registry-best-practices.md
  Articles/Blog/2021-09-CollegevilleReportDay1.md
  Articles/Blog/2021-09-SSwDiscoveriesInterview.md
  Articles/Blog/2021-10-CollegevilleReportDay2.md
  Articles/Blog/2021-10-FirstFiveYrsWebinar.md
  Articles/Blog/2021-11-CollegevilleReportDay3.md
  Articles/Blog/2021-11-HPCAndTheLabManager.md
  Articles/Blog/2021-12-sc21-swe-cse-bof.md
  Articles/Blog/2022-01-2022BSSwFellowshipAnnounce.md
  Articles/Blog/2022-02-precice-testing.md
  Articles/Blog/2022-02-sc21-correctness-workshop.md
  Articles/Blog/2022-03-sc21-rse-workshop.md
Labels: content: updates

#1896 Add Track to articles (#1558)
  Articles/Blog/2022-04-user-stories.md
  Articles/Blog/2022-04-wosss-workshop-series.md
  Articles/Blog/2022-05-build-integration-testing.md
  Articles/Blog/2022-05-trusted-cyberinfrastructure.md
  Articles/Blog/2022-06-Navigating-transition-to-cloud.md
  Articles/Blog/2022-06-Software-Deployment-Bringing-resources-into-effective-acction.md
  Articles/Blog/2022-07-BSSwFellows2021.md
  Articles/Blog/2022-07-vive-la-difference-rse.md
  Articles/Blog/2022-08-BSSwFellowsOpen2022.md
  Articles/Blog/2022-08-Team-of-Teams-Panel.md
  Articles/Blog/2022-08-brightspot-ci.md
  Articles/Blog/2022-08-scicodes-consortium.md
  Articles/Blog/2022-09-SoftwareVariants.md
  Articles/Blog/2022-09-peer-code-review.md
  Articles/Blog/2022-10-reading-list.md
  Articles/Blog/2022-11-visual-git.md
  Articles/Blog/2022-12-2023BSSwFellowshipAnnounce.md
  Articles/Blog/2022-12-MutualOwnershipInRSE.md
  Articles/Blog/2023-01-ecp-tutorials-bosf.md
  Articles/Blog/2023-02-anatomy-rse-team.md
  Articles/Blog/2023-03-08-productivity-practices-and-tools.md
  Articles/Blog/2023-03-Julia_for_BSSw.md
  Articles/Blog/2023-03-numfocus.md
  Articles/Blog/2023-04-developer-surveys.md
  Articles/Blog/2023-04-lowndes-fellowship-post.md
  Articles/Blog/2023-05-cise-rse-issues.md
  Articles/Blog/2023-05-sci-workflows.md
  Articles/Blog/2023-06-acm-rep.md
  Articles/Blog/2023-07-BSSwFellows2022.md
  Articles/Blog/2023-07-optimizing_io.md
  Articles/Blog/2023-08-BSSwFellowsOpen2023.md
  Articles/Blog/2023-08-Software-Gardening.md
  Articles/Blog/2023-08-containers-workflows.md
  Articles/Blog/2023-09-bsswf-blog-post.md
  Articles/Blog/2023-09-io-storage-characterization.md
  Articles/Blog/2023-10-fear-of-large-codes.md
  Articles/Blog/2023-10-intersect.md
  Articles/Blog/ATPESC.md
  Articles/Blog/AcceleratingScientificDiscoveryWithReusableSoftware.md
  Articles/Blog/AcceleratingScientificDiscoveryWithReusableSoftwareCiSE2019.md
Labels: content: updates, preview

#1874 Add GitHub Action using codespell to check files and commit msgs (#1864)
  .codespellrc
  .github/workflows/codespell.yml
  Articles/Blog/2023-02-anatomy-rse-team.md
  CuratedContent/PublishingCseSw.md
Labels: scope: site-internal

#1910 Update README.md
  README.md
Labels: content: updates

#1906 Update How-tos and add tracks
  Articles/Blog/DefinitionsCategorizationsOfTests.md
  Articles/Blog/UnderstandingCSESoftwareProductivity.md
  Articles/Blog/UnderstandingInteroperableLibraries.md
  Articles/Blog/UnderstandingSoftwareTestingPractices.md
  Articles/WhatIs/WhatAreInteroperableSwLibraries.md
  Articles/WhatIs/WhatIsCseSwTesting.md
  HowTos/WhatAreInteroperableLibraries.md
  images/HowTo_Understand_CSE_Productivity.png
Labels: content: howto, preview

#1908 Update how-tos and tracks (set 2)
  Articles/Blog/RequirementsInScientificComputing.md
  Articles/Blog/UnderstandingGoodDocumentation.md
  Articles/ShortArticles/Part1-RequirementsAndRequirementsEngineering.md
  Articles/ShortArticles/Part2-UnderstandingRequirements.md
  Articles/ShortArticles/Part3-WritingRequirements.md
  Articles/ShortArticles/Part4-UnderstandingPerformingRequirementsEngineering.md
  Articles/ShortArticles/Part5-PerformingRequirementsEngineeringREVISE.md
  Articles/WhatIs/WhatIsGoodDocumentation.md
  HowTos/WhatIsGoodDocumentation.md
Labels: content: howto, preview

#1912 Assorted updates
  Articles/Blog/README.md
  Articles/README.md
  Articles/WhatIs/WhatAreConferencesAndWorkshops.md
  Articles/WhatIs/WhatAreCseSwDevptTools.md
  Articles/WhatIs/WhatAreCseSwRequirements.md
  Articles/WhatIs/WhatAreDiscussionAndQuestionSitesForBetterScientificSw.md
  Articles/WhatIs/WhatAreFundingSourcesAndProgramsAddressingBetterScientificSw.md
  Articles/WhatIs/WhatAreProjectsAndOrganizationsAddressingBetterScientificSw.md
  Articles/WhatIs/WhatAreStrategiesForMoreEffectiveTeams.md
  Articles/WhatIs/WhatAreSwCodingStandards.md
  Articles/WhatIs/WhatIsContinuousIntegrationTesting.md
  Articles/WhatIs/WhatIsCseLegacyCode.md
  Articles/WhatIs/WhatIsCseSwDevelopment.md
  Articles/WhatIs/WhatIsCseSwDistribution.md
  Articles/WhatIs/WhatIsCseSwRefactoring.md
  Articles/WhatIs/WhatIsDebugging.md
  Articles/WhatIs/WhatIsProductivity.md
  Articles/WhatIs/WhatIsReproducibility.md
  Articles/WhatIs/WhatIsRevisionControl.md
  Articles/WhatIs/WhatIsSampleTopic.md
  Articles/WhatIs/WhatIsSoftwareIntellectualProperty.md
  Articles/WhatIs/WhatIsSustainability.md
  Articles/WhatIs/WhatIsSwConfiguration.md
  Articles/WhatIs/WhatIsSwEngForCse.md
  Articles/WhatIs/WhatIsWorkOnSwPublishingAndCitation.md
  CuratedContent/README.md
  Events/README.md
Labels: content: updates, preview

#1915 Feedback on Marks howto article updates #1905
  Articles/Blog/HowToEnablePerformancePortability.md
  Articles/Blog/HowToVersionControlwithGit.md
  Articles/Blog/HowToWriteGoodDocumentation.md
  Articles/Blog/HowtoImproveTestinginyourCSESoftwareProject.md
Labels: content: howto, content: updates, preview

#1905 Reformat articles for blog and add tracks
  Articles/Blog/2023-07-optimizing_io.md
  Articles/Blog/HowToEnablePerformancePortability.md
  Articles/Blog/HowToVersionControlwithGit.md
  Articles/Blog/HowToWriteGoodDocumentation.md
  Articles/Blog/HowtoImproveTestinginyourCSESoftwareProject.md
  CuratedContent/HowToDoVersionControlWithGitInYourCseProject.md
  CuratedContent/HowToEnablePerfPortabilityForCseApps.md
  CuratedContent/HowToImproveTestingForCseSw.md
  CuratedContent/HowToWriteGoodDocumentation.md
Labels: content: howto, preview

#1917 Remove the checking of git commit message (#1916)
  .github/workflows/codespell.yml
Labels: scope: site-internal

#1918 Reformat short articles for blog
  Articles/Blog/BSSwFellows2018ProjectsAndPerspectives.md
  Articles/Blog/BSSwSiteHasANewIntegratedContentMap.md
  Articles/Blog/CodingConventions.md
  Articles/Blog/ContainersForResearchSw.md
Labels: content: updates, preview

#1922 Create WhatIsPerformanceAtLCFs.md
  Articles/WhatIs/WhatIsPerformanceAtLCFs.md
Labels: content: whatis, content: updates, preview

#1923 Cleanup what-is: better planning category
  Articles/WhatIs/WhatAreCseSwRequirements.md
  Articles/WhatIs/WhatIsCseSwDesign.md
  Articles/WhatIs/WhatIsSwEngForCse.md
  Articles/WhatIs/WhatIsSwProductivity.md
  Articles/WhatIs/WhatIsSwSustainability.md
Labels: content: whatis, content: updates, preview

#1924 Working on How To Articles
  Articles/Blog/UnderstandingPerfPortabilityForCSEApps.md
  Articles/Blog/UnderstandingSoftwareConfiguration.md
  Articles/Blog/VersionControlSystems.md
  Articles/WhatIs/WhatIsPerfPortabilityForCseApps.md
  Articles/WhatIs/WhatIsRevisionControl.md
  Articles/WhatIs/WhatIsSwConfiguration.md
Labels: content: howto, preview

#1927 Move short articles to blog folder and minor formatting
  Articles/Blog/TheDeveloperCertificateOfOrigin.md
  Articles/Blog/TipsOnlinePanels.md
  Articles/Blog/UnitTestingC++WithCatch.md
  Articles/Blog/UserStories.md
  Articles/Blog/WhatPerfPortabilityToolsAreCompatible.md
Labels: content: updates, preview

#1925 Reformat for blog
  Articles/ShortArticles/PullRequestSizeConsiderations.md
Labels: content: updates, preview

#1929 Cleaning What-is files to point to how-to blogs
  Articles/WhatIs/WhatAreConferencesAndWorkshops.md
  Articles/WhatIs/WhatAreCseSwDevptTools.md
  Articles/WhatIs/WhatAreInteroperableSwLibraries.md
  Articles/WhatIs/WhatIsCseSwTesting.md
  Articles/WhatIs/WhatIsDebugging.md
  Articles/WhatIs/WhatIsGoodDocumentation.md
Labels: content: whatis, content: updates, preview

#1930 Move short articles to Blogs
  Articles/Blog/DiscontinuingSoftwareProjects.md
  Articles/Blog/OpenssfBestPracticesBadgeProgram.md
  Articles/Blog/PullRequestSizeConsiderations.md
  Articles/Blog/TelecomToolsForRemoteWork.md
  Articles/Blog/UnitTestingC++WithCatch.md
  Articles/ShortArticles/README.md
Labels: content: updates, preview

#1931 Update how-tos and reformat them to blogs
  Articles/Blog/CriticalBeginnerGitUsageTips.md
  Articles/Blog/GitTutorialReferenceCollection.md
  Articles/Blog/HowToConfigureSw.md
  HowTos/README.md
Labels: content: howto, content: updates, preview

#1897 Create HM_Test1_2023.md
  Articles/Blog/2023-12-2024BSSwFellowshipAnnounce.md
  Site/Announcements/Announcements.md
  Site/BSSwFellowshipProgram/People/2024-F-Bunten.md
  Site/BSSwFellowshipProgram/People/2024-F-Jarecka.md
  Site/BSSwFellowshipProgram/People/2024-F-Newton.md
  Site/BSSwFellowshipProgram/People/2024-F-Raffenetti.md
  Site/BSSwFellowshipProgram/People/2024-F-Richard.md
  Site/BSSwFellowshipProgram/People/2024-F-Wasser.md
  Site/BSSwFellowshipProgram/People/2024-HM-Georgiadou.md
  Site/BSSwFellowshipProgram/People/2024-HM-Marquez.md
  Site/BSSwFellowshipProgram/People/2024-HM-Paine.md
  Site/BSSwFellowshipProgram/People/2024-HM-Ross.md
  Site/BSSwFellowshipProgram/People/2024-HM-Scarpino.md
  Site/BSSwFellowshipProgram/People/2024-HM-Scourtas.md
  images/Blog_2312_Bunten_F.png
  images/Blog_2312_Georgiadou_HM.png
  images/Blog_2312_Jarecka_F.png
  images/Blog_2312_Marquez_HM.png
  images/Blog_2312_Newton_F.png
  images/Blog_2312_Paine_HM.png
  images/Blog_2312_Raffenetti_F.png
  images/Blog_2312_Richard_F.png
  images/Blog_2312_Ross_HM.png
  images/Blog_2312_Scarpino_HM.png
  images/Blog_2312_Scourtas_HM.png
  images/Blog_2312_Wasser_F.png
  images/People-2024-F-Bunten.jpg
  images/People-2024-F-Jarecka.jpg
  images/People-2024-F-Newton.jpg
  images/People-2024-F-Raffenetti.jpg
  images/People-2024-F-Richard.jpg
  images/People-2024-F-Wasser.jpg
  images/People-2024-HM-Georgiadou.jpg
  images/People-2024-HM-Marquez.jpg
  images/People-2024-HM-MarquezB.jpg
  images/People-2024-HM-Paine.jpg
  images/People-2024-HM-PaineB.jpg
  images/People-2024-HM-Ross.jpg
  images/People-2024-HM-RossB.jpg
  images/People-2024-HM-Scarpino.jpg
  images/People-2024-HM-Scourtas.jpg
  images/People-2024-HM-ScourtasB.jpg
Labels: preview

#1941 Create S3C conference event
  Events/2024-04-s3c-conference.md
Labels: content: event, preview

#1866 add Summer of Reproducibility blog post
  Articles/Blog/2023-12-ucsc-sor.md
  images/Blog_2312_ucsc-sor.png
Labels: preview, external contribution

#1942 Change pub date
  Articles/Blog/OpenssfBestPracticesBadgeProgram.md
Labels: content: curated, content: updates, preview

#1940 Create event for HiRSE webinar 24 in January
  Events/hirse-024-2024-01.md
Labels: content: event, preview

#1948 December Carousel
  Site/Homepage.md
Labels: content: updates, preview

#1949 Adding missing track to blog
  Articles/Blog/2023-09-secure-sci-software-dev.md
Labels: content: updates, preview

#1933 Adding BSSw fellowship track and some articles
  Articles/Blog/2020-12-2021BSSwFellowshipAnnouncement.md
  Articles/Blog/2021-03-2021BSSwFellowshipNSFAnnouncement.md
  Articles/Blog/2021-04-SWMetricsInResearch.md
  Articles/Blog/2021-07-BSSwFellows21.md
  Articles/Blog/2022-01-2022BSSwFellowshipAnnounce.md
  Articles/Blog/2022-06-Navigating-transition-to-cloud.md
  Articles/Blog/2022-07-BSSwFellows2021.md
  Articles/Blog/2022-08-BSSwFellowsOpen2022.md
  Articles/Blog/2022-12-2023BSSwFellowshipAnnounce.md
  Articles/Blog/2023-04-lowndes-fellowship-post.md
  Articles/Blog/2023-07-BSSwFellows2022.md
  Articles/Blog/2023-07-optimizing_io.md
  Articles/Blog/2023-08-BSSwFellowsOpen2023.md
  Articles/Blog/2023-08-containers-workflows.md
  Articles/Blog/2023-09-bsswf-blog-post.md
  Articles/Blog/2023-09-io-storage-characterization.md
  Articles/Blog/2023-09-secure-sci-software-dev.md
  Articles/Blog/BSSwFellows2018ProjectsAndPerspectives.md
  Articles/Blog/BSSwFellowsAnnouncement.md
  Articles/Blog/BSSwFellowsAnnouncement2019.md
  Articles/Blog/BSSwFellowshipAnnouncement2020.md
  Articles/Blog/BSSwFellowshipApplicationsOpen.md
  Articles/Blog/BSSwFellowshipApplicationsOpen2018.md
  Articles/Blog/BSSwFellowshipApplicationsOpen2019.md
  Articles/Blog/BSSwFellowshipApplicationsOpen2020.md
  Articles/Blog/BSSwFellowshipApplicationsOpen2021.md
  Articles/Blog/BSSwFellowshipKatzIntroduction.md
  Articles/Blog/BSSwFellowshipProgramFAQ.md
  Articles/Blog/IncreasingProductivityBroadeningParticipation.md
  Articles/Blog/TestingNondeterministicResearchSoftware.md
  Articles/BlogTracks.md
Labels: type: enhancement, content: updates, preview

#1952 EB docs: Update blog section and grammar/typo corrections
  docs/pages/bssw/bssw_content_metadata.md
  docs/pages/bssw/bssw_content_overview.md
  docs/pages/bssw/bssw_content_placement.md
  docs/pages/bssw/bssw_styling_common.md
  docs/pages/bssw/bssw_styling_originalarticles.md
  docs/pages/bssw/bssw_teamresponsibilites.md
Labels: content: updates, type: documentation

#1953 EB docs: corrections and typos
  docs/_data/sidebars/bssw_sidebar.yml
  docs/pages/bssw/bssw_add_new_topics.md
  docs/pages/bssw/bssw_styling_common.md
Labels: content: updates, type: documentation

#1954 EB docs and examples: For interview style articles
  Articles/Blog/InclusiveLanguageCodeUpdateExample.md
  docs/pages/bssw/bssw_styling_originalarticles.md
Labels: content: updates, preview, type: documentation

#1955 EB docs: Add section on adding new tracks
  docs/_data/sidebars/bssw_sidebar.yml
  docs/pages/bssw/bssw_add_new_tracks.md
Labels: type: documentation

#1956 EB docs: documenting dates
  docs/_data/sidebars/bssw_sidebar.yml
  docs/pages/bssw/bssw_content_overview.md
  docs/pages/bssw/bssw_styling_event.md
Labels: content: updates, type: documentation

#1958 Minor updates to bssw_styling_event.md
  docs/pages/bssw/bssw_styling_event.md
Labels: content: updates, type: documentation

#1959 EB docs: Fixing typos and broken urls
  docs/pages/bssw/bssw_styling_event.md
Labels: content: updates, type: documentation
