Repository betterscientificsoftware/bssw.io, pull requests merged in 2024-09, with the labels that each got.

#2153 Create 2024-09-clarity-and-community-gained.md
  Articles/Blog/2024-09-clarity-and-community-gained.md
  Site/Homepage.md
Labels: preview

#2154 slides for the 2025 BSSwF Q&A Session
  Site/BSSwFellowshipProgram/FellowsFAQ.md
Labels: external contribution

#2155 bsswf25 link to video recording
  Site/BSSwFellowshipProgram/FellowsFAQ.md
Labels: external contribution

#2156 Create 2024-09-inspired-engagement.md
  Articles/Blog/2024-09-inspired-engagement.md
Labels: preview

#2162 Create 2024-09-better-teams-software-community.md
  Articles/Blog/2024-09-better-teams-software-community.md
Labels: preview

#2160 OSSFE conference event file
  Events/2025-03-ossfe.md
Labels: content: event, preview, external contribution

#2139 Blog: Technical properties of sustainable software
  Articles/Blog/2024-09-TechnicalPropertiesOfSustainableSoftware.md
  images/2024-08-TechnicalPropertiesOfSustainableSoftware-hero-image.jpg
Labels: content: blog, preview

#2167 Correct typo in Planning.md
  Site/Topics/Planning.md
Labels: content: updates, preview

#2165 Create 2024-09-cultivating-collaboration-skills.md
  Articles/Blog/2024-09-cultivating-collaboration-skills.md
Labels: preview

#2164 Sep carousel
  Site/Homepage.md
Labels: content: updates, preview
