Repository betterscientificsoftware/bssw.io, pull requests merged in 2025-04, with the labels that each got.

#2285 Create close-milestones.yml
  .github/workflows/close-milestones.yml
Labels: type: enhancement, scope: site-internal

#2286 Create add-milestone.yml
  .github/workflows/add-milestone.yml
Labels: type: enhancement, scope: site-internal

#2289 Test of milestone workflow (2)
  .github/workflows/issue-to-project.yml
Labels: scope: site-internal, type: test content

#2293 Check whether the PR has been merged or just closed
  .github/workflows/add-milestone.yml
Labels: type: enhancement, scope: site-internal

#2294 Test of milestone workflow (5)
  .github/workflows/issue-to-project.yml
Labels: content: blog

#2296 Trigger milestone closer on a schedule
  .github/workflows/close-milestones.yml
Labels: type: enhancement, scope: site-internal

#2254 Blog: "Growing resilient scientific software ecosystems: Introducing the Software Gardening Almanack"
  Articles/Blog/2025-04-Software-Gardening-Almanack.md
  images/French_Orchard_at_Harvest_Time_(Le_verger)_(SM_1444).png
  images/almanack-future2.png
  images/normalized-shannon-entropy-per-file-formula.png
  images/shannon-entropy-formula.png
  images/software-entropy-relationships.png
  images/software-gardening-almanack-components.png
  images/software-gardening-almanack-demo.png
  images/software-gardening-almanack-package.png
  images/software-gardening-lifecycle.png
Labels: content: blog, preview, external contribution

#2301 Update URLs
  Articles/Blog/2024-06-generating-SBOMs.md
  Articles/Blog/OpenssfBestPracticesBadgeProgram.md
  CuratedContent/NationalCyberDirectorRFI.md
Labels: content: updates

#2300 Ken Raffenetti blog
  Articles/Blog/2025-04-mpi-performance.md
Labels: content: blog, preview

#2305 Update Carousel.md for April 2025
  Site/Homepage.md
Labels: content: updates, preview

#2303 Fix links to files on GitHub that changed directory name
  Articles/Blog/OpenssfBestPracticesBadgeProgram.md
Labels: preview
